name: Deploy CLAuS Shiny App

on:
  push:
    branches: [ main ]  # or your default branch name
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight UTC


jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      RSPM: https://packagemanager.rstudio.com/cran/__linux__/focal/latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ~/.cache/R
          key: ${{ runner.os }}-r-${{ hashFiles('.github/workflows/deploy.yml') }}
          restore-keys: ${{ runner.os }}-r-

      - name: Install dependencies
        run: Rscript -e 'install.packages(c("remotes"))' && Rscript -e 'remotes::install_cran(c("shiny","googlesheets4","dplyr","tibble","stringr","readr","tidyr","rsconnect"))'

      - name: Generate updated standings and results
        run: Rscript -e 'source("app.R", local=TRUE)' 

      - name: Deploy to shinyapps.io
        env:
          SHINYAPPS_ACCOUNT_NAME: ${{ secrets.SHINYAPPS_ACCOUNT_NAME }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          R -e "rsconnect::setAccountInfo(name='${SHINYAPPS_ACCOUNT_NAME}', token='${SHINYAPPS_TOKEN}', secret='${SHINYAPPS_SECRET}')"
          R -e "rsconnect::deployApp('.', forceUpdate=TRUE)"
